import { Bank } from "@/types";

export const BANKS: Bank[] = [
  {
    id: "hbl",
    name: "HBL",
    logo: "🏦",
    color: "#006B3F",
    offersUrl: "https://www.hbl.com/personal/cards/hbl-deals-and-discounts",
    dealsWidgetUrl: "https://hbl-web.peekaboo.guru/",
    cardTypes: [
      "All Cards",
      "HBL Visa Infinite CreditCard",
      "HBL Platinum CreditCard",
      "HBL World Elite DebitCard",
      "HBL World DebitCard",
      "HBL Gold CreditCard",
      "HBL Gold DebitCard",
      "HBL Green CreditCard",
      "HBL Titanium DebitCard",
      "HBL DebitCard",
      "HBL Konnect Debit Card",
      "QR - Scan to Pay",
      "HBL Classic Business DebitCard",
      "HBL Nisa DebitCard",
      "HBL UnionPay Classic DebitCard",
      "HBL UnionPay Gold DebitCard",
      "HBL UPI & PayPak Co-Badge DebitCard",
      "HBL World Business DebitCard",
    ],
  },
  {
    id: "mcb",
    name: "MCB",
    logo: "🏛️",
    color: "#F58220",
    offersUrl: "https://www.mcb.com.pk/personal/cards",
    dealsWidgetUrl: "https://mcb-web.peekaboo.guru/",
    cardTypes: [
      "All Cards",
      "Visa Signature Debit Card",
      "Visa Platinum Credit Card",
      "Visa Platinum Debit Card",
      "Nayab Visa Debit Card",
      "Visa Gold Credit Card",
      "Visa Gold Debit Card",
      "Visa Classic Credit Card",
      "Visa Silver Debit Card",
      "PayPak Gold Debit Card",
      "PayPak Classic Debit Card",
      "Visa Fun Club Debit Card",
    ],
  },
  {
    id: "ubl",
    name: "UBL",
    logo: "🏢",
    color: "#0065A3",
    offersUrl: "https://www.ubldigital.com/Discounts",
    dealsWidgetUrl: "https://ubl-web.peekaboo.guru/",
    cardTypes: [
      "All Cards",
      "UBL Visa Infinite Debit Card",
      "Mastercard Signature Debit Card",
      "UBL Visa Platinum Credit Card",
      "UBL Visa Gold Credit Card",
      "UBL Mastercard Premium Debit Card",
      "UBL VISA Premium Debit Card",
      "UBL Urooj Visa Debit Card",
      "UBL Ameen VISA Premium Debit Card",
      "UBL Ameen Premium Debit Mastercard",
      "UBL Visa Classic Credit Card",
      "UBL Ameen PayPak Debit Card",
      "UBL Pay Pak Debit Card",
      "UBL Union Pay Debit Card",
      "UBL Mastercard WIZ Virtual Prepaid Card",
      "UBL Visa Freelancer Debit Card",
      "UBL Visa Premium Plus Debit Card",
      "Visa FCY Business Debit Card",
    ],
  },
  {
    id: "faysal",
    name: "Faysal Bank",
    logo: "🟦",
    color: "#003A6A",
    offersUrl: "https://www.faysalbank.com",
    dealsWidgetUrl: "https://faysalbank-web.peekaboo.guru/",
    cardTypes: [
      "All Cards",
      "Faysal Islami Noor World Card",
      "Faysal Islami Mastercard Classic Debit Card",
      "Faysal Islami Noor Velocity Card",
      "Amal Mastercard Gold Debit Card",
      "Faysal Islami Mastercard Gold Debit Card",
      "Faysal Islami Noor Gold Card",
      "Faysal Islami Noor Titanium Card",
      "Amal Mastercard Platinum Debit Card",
      "Faysal Islami Priority Platinum Debit Card",
      "Faysal Islami Noor Platinum Card",
      "Faysal Bank Business Debit Card",
      "Faysal Islami Co-Badged Mastercard Paypak Debit Card",
      "Faysal Islami Noor Flexi Card",
      "Faysal Islami Paypak Debit Card",
      "Faysal Islami Priority World Debit Card",
    ],
  },
  {
    id: "allied",
    name: "Allied Bank",
    logo: "🔶",
    color: "#F58220",
    offersUrl: "https://www.abl.com/personal-banking/cards",
    dealsWidgetUrl: "https://allied-web.peekaboo.guru/",
    cardTypes: [
      "All Cards",
      "Visa Infinite Debit Card",
      "Visa Premium Debit Card",
      "Visa Platinum Debit Card",
      "Visa Platinum Credit Card",
      "Visa Gold Credit Card",
      "Gold UPI & PayPak Debit Card",
      "Cash+Shop Sapphire 200 Visa Debit Card",
      "Cash+Shop Sapphire Visa Debit Card",
      "Cash+Shop Classic Visa Debit Card",
      "Youth VISA DebitCard",
      "Classic UPI & PayPak Debit Card",
      "Classic Plus UPI & PayPak Debit Card",
      "Islamic Banking VISA DebitCard",
      "UPI & Paypak myWallet Debit Card",
      "myABL Mastercard QR",
      "Khanum Classic Plus UPI & PayPak Debit Card",
      "UnionPay PayPak Basic Debit Card",
      "UnionPay PayPak Prepaid Card",
    ],
  },
  {
    id: "mcbislamic",
    name: "MCB Islamic",
    logo: "🕌",
    color: "#F58220",
    offersUrl: "https://www.mcbislamicbank.com",
    dealsWidgetUrl: "https://mcb-islamic-web.peekaboo.guru/",
    cardTypes: [
      "All Cards",
      "Visa Platinum Business Debit Card",
      "Visa Platinum Debit Card",
      "Visa Gold Debit Card",
      "Visa FCY Debit Card",
      "Visa Classic Debit Card",
      "Visa Niswan Debit Card",
      "Visa Junior Club Debit Card",
      "UnionPay Platinum Debit Card",
      "UnionPay Qadar Gold Debit Card",
      "UnionPay Qadar Classic Debit Card",
      "PayPak Classic Debit Card",
    ],
  },
  {
    id: "meezan",
    name: "Meezan Bank",
    logo: "🌙",
    color: "#642054",
    offersUrl: "https://www.meezanbank.com/discounts/",
    dealsWidgetUrl: "https://meezan-web.peekaboo.guru/",
    cardTypes: [
      "All Cards",
      "Visa Infinite Debit Card",
      "Mastercard World Debit Card",
      "Platinum Mastercard Debit Card",
      "Platinum Visa Debit Card",
      "Titanium Mastercard Debit Card",
      "Gold Visa Debit Card",
      "Classic Mastercard Debit Card",
      "Classic Visa Debit Card",
      "Kids Club Visa Debit Card - Boys",
      "PayPak Debit Card",
      "Kids Club Visa Debit Card - Girls",
      "Visa Charge Card",
      "Visa Student Debit Card",
      "Visa Women First Debit Card",
    ],
  },
  {
    id: "alfalah",
    name: "Bank Alfalah",
    logo: "🔴",
    color: "#DA291C",
    offersUrl: "https://www.bankalfalah.com/discounts/",
    dealsWidgetUrl: "https://alfalah-web.peekaboo.guru/",
    cardTypes: [
      "All Cards",
      "Bank Alfalah Visa Platinum Credit Card",
      "Bank Alfalah American Express Gold Credit Card",
      "Bank Alfalah Islamic Power Pack Signature Debit Card",
      "Bank Alfalah Islamic Premier Visa Infinite Debit Card",
      "Bank Alfalah Islamic Premier Visa Signature Debit Card",
      "Bank Alfalah Islamic Women Power Pack Visa Debit Card",
      "Bank Alfalah Islamic Women Visa Gold Debit Card",
      "Bank Alfalah Mastercard Optimus Credit Card",
      "Bank Alfalah Mastercard Titanium Credit Card",
      "Bank Alfalah PayPak Classic Debit Card",
      "Bank Alfalah PayPak Islamic Classic Debit Card",
      "Bank Alfalah Pehchaan Visa Debit Card",
      "Bank Alfalah Premier Visa Infinite Credit Card",
      "Bank Alfalah Premier Visa Infinite Debit Card",
      "Bank Alfalah Premier Visa Platinum Credit Card",
      "Bank Alfalah Premier Visa Signature Debit Card",
      "Bank Alfalah Ultra Visa Credit Card",
      "Bank Alfalah Visa Classic Credit Card",
      "Bank Alfalah Visa Classic Debit Card",
      "Bank Alfalah Visa Corporate Credit Card",
      "Bank Alfalah Visa Gold Credit Card",
      "Bank Alfalah Visa Gold Debit Card",
      "Bank Alfalah Visa Islamic Classic Debit Card",
      "Bank Alfalah Visa Islamic Gold Debit Card",
      "Bank Alfalah Visa Islamic Signature Debit Card",
      "Bank Alfalah Visa Platinum Debit Card",
      "Bank Alfalah Visa Signature Debit Card",
    ],
  },
];

export const CITIES = ["Lahore", "Karachi", "Islamabad", "Rawalpindi", "Faisalabad"];

export function getBankById(id: string): Bank | undefined {
  return BANKS.find((b) => b.id === id);
}
